### PR TITLE
added "remove" command

### PR DESCRIPTION
**Pull request by rlKoekie**
Hi again,

I added the remove command, and wrote a small example of username/password authentication in the Readme.
I did not manage to figure out how to run the testset, maybe somebody can add the test for the remove command.

### CODE REVIEW

**Comment by rlKoekie** [comment]
I think I managed to squash the commits. (sorry, I'm an SVN guy... that's why I use pysvn :-)

**Comment by tusharmakkar08** [comment]
Yes, it is done :)

**Comment by jfthuong** [comment]
@dsoprea This MR could be closed as `remove` is now present in both "local" and "remote"

**Comment by rlKoekie** [comment]
closing it

**Pull request closed without merging**
