### PR TITLE
Added changelist functionality to log_default() function

### PR DESCRIPTION
**Pull request by kris1250**
Added the option to get changelist info for each revision.

### CODE REVIEW

**Comment by mheppner** [comment]
Any idea when this will be merged and bumped to PyPI?

**Comment by dsoprea** [comment]
ASAP. If not done within two days, bump please.

Thanks for contributing, Mark.

Dustin

**Comment by dsoprea** [comment]
Looks good. Can you rebase (rebase -i) and collapse the two useless commits?

**Comment by kris1250** [comment]
I kept getting errors trying to push my rebase. Are you able to squash the commits through the github UI?

**Comment by dsoprea** [comment]
I don't think so, but you'll have to clean it up and convince that you're not going to compromise *master* if we were to merge since it seems like there might be some broken structure on your local checkout. If that's the case then do a new clone, make sure nothing has changed in the relevant places, copy the files over, and commit. This will have the same net effect (less commits).

If that's not the case then you must be messing-up the command somehow:

git rebase -i HEAD~N (where N is the number of recent commits to include in the rebase). On that screen, leave all of the lines alone except for those that you want to squash. Keep in mind that you can't/shouldn't squash the first line and that you'll be prompted to edit the commit for each set of adjacent squashes. I don't except this to be the case since you're only trying to remove a couple of adjacent commits, but, FYI, sometimes it's nicer to do multiple squashes, where each rebase operation only includes adjacent squashes.

If you still don't know what do with this then just go ahead and push and I'll do the rebase (to help you out).

**Comment by kris1250** [comment]
Yea I was doing "git rebase -i HEAD~3" and then removed the lines I wanted to squash. I've been using svn for the past few months (thats what my work uses) so my git skills are a bit rusty. I think it would be cleaner and easier to refork the repo and then do it right the first time

**Pull request closed without merging**
