### PR TITLE
Added def for 'Update'

### PR DESCRIPTION
**Pull request by caboose014**

### CODE REVIEW

**Comment by dsoprea** [comment]
Thanks for contributing. Can you remove the *.idea* directory?

**Comment by caboose014** [comment]
Sorry for the delay! I have removed the .idea folder now.

**Comment by IARI** [comment]
I'm interested in this.
@dsoprea any reason this pr should not be merged the way it is now?

**Comment by dsoprea** [comment]
Sorry about the delay. I'll try to catch-up today on this and some others
today.

Dustin

**Comment by IARI** [comment]
Sorry, I don't mean to be annoying ^^
But is there anything that needs to be changed before it can be merged? :)
I can offer to minimize the diffs (remove the changed @caboose014 made to formating), so merging will be easier, if that helped?

**Comment by dsoprea** [comment]
This got past me. Sorry for the delay.

There are a few other arbitrary changes. There are a bunch of unnecessary formatting changes and you bumped the version (which I should only do right before a release). If you can get rid of those things and resolve the conflicts, I'll merge.

Since it's been a little time, now, I'm going to close. If you make the changes, please reopen.

**Pull request closed without merging**
